name: Testing
on: [pull_request]
permissions:
  contents: read

jobs:

  static_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 } # deep clone for setuptools-scm
      - uses: actions/setup-python@v4
        with: { python-version: "3.11" }
      - name: Run static analysis and format checkers
        run: pipx run pre-commit run --all-files --show-diff-on-failure

  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        platform:
          - ubuntu-latest
    env:
      OS: ${{ matrix.platform }}
      PYTHON: ${{ matrix.python }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install pipenv
        run: pip install pipenv

      - name: install dependencies
        run: pipenv install --ignore-pipfile --dev --python ${{ matrix.python-version }}

      - name: pytest
        run: pipenv run pytest
